export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST"
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS"
export const FETCH_NEWS_FAIL = "FETCH_NEWS_FAIL"

export const FETCH_SINGLE_NEWS_REQUEST = "FETCH_SINGLE_NEWS_REQUEST"
export const FETCH_SINGLE_NEWS_SUCCESS = "FETCH_SINGLE_NEWS_SUCCESS"
export const FETCH_SINGLE_NEWS_FAIL = "FETCH_SINGLE_NEWS_FAIL"