import {FETCH_NEWS_SUCCESS, FETCH_NEWS_FAIL,FETCH_NEWS_REQUEST, FETCH_COMMENT_REQUEST,FETCH_COMMENT_SUCCESS,FETCH_COMMENT_FAIL} from "./actions"

export {FETCH_NEWS_SUCCESS, FETCH_NEWS_FAIL,FETCH_NEWS_REQUEST,FETCH_COMMENT_REQUEST,FETCH_COMMENT_SUCCESS,FETCH_COMMENT_FAIL }